#!/bin/bash

LAMBDA_FUNCTION_NAME="billing-pdf-collector"
ZIP_FILE="package.zip"
REGION="ap-southeast-2"

# if zip file does not exist, exit
if [ ! -f "$ZIP_FILE" ]; then
  echo "File $ZIP_FILE does not exist. Please run 'auto/build' and 'auto/package' first."
  exit 1
fi

echo "Updating lambda function $LAMBDA_FUNCTION_NAME in region $REGION with $ZIP_FILE"
aws lambda update-function-code \
  --region $REGION \
  --function-name $LAMBDA_FUNCTION_NAME \
  --zip-file fileb://package.zip \
  --profile pct