name: Lambda Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install the dependencies
        run: npm ci

      - name: Audit packages
        run: npm audit

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build files
        run: ./auto/build

      - name: Prepare Lambda ZIP file
        run: ./auto/package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-package
          path: package.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda-package

      - name: Deploy lambda
        run: ./auto/publish